server:
  port: 8081
spring:
  thymeleaf:
    cache: false

# AI服务配置
ai:
  # Ollama配置
  ollama:
    base-url: http://localhost:11434
    api-path: /api/chat
    model: deepseek-r1:7b
    timeout: 30000
  # DeepSeek配置
  deepseek:
    base-url: https://api.deepseek.com
    api-path: /v1/chat/completions
    model: deepseek-chat
    timeout: 30000
  # 天气API配置
  weather:
    base-url: https://wttr.in
    timeout: 10000 